spring:
  redis:
    host: 192.168.1.28
    password: 123456
    port: 6379
    ssl: false
    timeout: 300
    jedis:
      pool:
        max-active: 800
        max-idle: 20
        max-wait: -1
        min-idle: 0